## Deliverable 2. Create a Customer Travel Destinations Map.

In [4]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [5]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Santona,ES,43.4439,-3.4576,22.17,90,100,3.85,overcast clouds
1,1,Hithadhoo,MV,-0.6000,73.0833,27.80,71,76,1.18,broken clouds
2,2,Chernyshevskiy,RU,63.0128,112.4714,8.94,84,100,2.62,overcast clouds
3,3,Tadine,NC,-21.5500,167.8833,23.47,67,100,8.18,overcast clouds
4,4,Praxedis Guerrero,MX,31.3667,-106.0167,31.72,26,44,1.13,scattered clouds

In [6]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 10
What is the maximum temperature you would like for your trip? 15

In [25]:
# 3. Filter the city_data_df DataFrame using the input statements 
#    to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]

In [26]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                115
City                   115
Country                110
Lat                    115
Lng                    115
Max Temp               115
Humidity               115
Cloudiness             115
Wind Speed             115
Current Description    115
dtype: int64

In [27]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_preferred_cities_df = preferred_cities_df.dropna()

In [30]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
8,New Norfolk,AU,12.18,overcast clouds,-42.7826,147.0587,
12,Keroka,KE,12.38,overcast clouds,-0.7758,34.9453,
15,Esperance,AU,12.91,broken clouds,-33.8667,121.9000,
17,Busselton,AU,14.25,few clouds,-33.6500,115.3333,
19,Broken Hill,AU,13.95,few clouds,-31.9500,141.4333,
20,Saskylakh,RU,11.56,broken clouds,71.9167,114.0833,
22,Beian,NO,13.34,broken clouds,63.6559,9.5683,
23,Mar Del Plata,AR,13.94,light rain,-38.0023,-57.5575,
34,Bredasdorp,ZA,10.06,light rain,-34.5322,20.0403,
37,Castro,BR,11.79,overcast clouds,-24.7911,-50.0119,

In [31]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row['Lat']
    lng = row['Lng']
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name
    try:
        print(f'Found {hotels["results"][0]["name"]} for {hotel_df["City"][index]}')
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    # If a hotel isn't found skip the city.
    except (IndexError): 
        print("No hotel found...skipping.")

Found The Shingles Riverside Cottages for New Norfolk
Found Bunker Hotel Keroka for Keroka
Found Hospitality Esperance for Esperance
Found Observatory Guest House for Busselton
Found Royal Exchange Hotel for Broken Hill
No hotel found...skipping.
Found Fjord-Fishing AS, Property & Housing Co. for Beian
Found Gran Hotel Mar del Plata for Mar Del Plata
Found Bredasdorp Country Manor for Bredasdorp
Found CHACARA BAILLY for Castro
Found Отке17.ру — жильё для командированных for Anadyr
Found St Ives Hobart Accommodation Tasmania for Hobart
Found Kaitangata Motor Camp for Kaitangata
Found Radisson Blu Hotel Waterfront, Cape Town for Cape Town
Found Best Western Kodiak Inn for Kodiak
Found The Halyards Hotel for Port Alfred
Found Port Lincoln Hotel for Port Lincoln
Found Gostinitsa for Ayan
Found Hotel Boutique Las Azucenas for Constitucion
Found "Khatanga" for Khatanga
Found Asyly-Kul' for Davlekanovo
Found Casa Maquia for Lata
Found Holiday Inn Express Antofagasta, an IHG Hotel for Antofagasta
Found Ellie's Villa for Mataura
Found Bluff Homestead - Guesthouse & Campervan Park for Bluff
Found Sapphire City Motor Inn for Inverell
Found Gostinitsa V Kose for Kosa
Found Kak Doma for Severo-Kurilsk
Found The Commodore for Mount Gambier
Found 39 On Nile Guest House for Port Elizabeth
Found End of The Road Ltd. for Tuktoyaktuk
Found Gostevoy Dom Mini Gostinitsa for Orlik
No hotel found...skipping.
Found The Esplanade Resort & Spa for Lakes Entrance
Found Hotel Cristal for Viedma
Found Hotel Arctic for Ilulissat
Found Gostinitsa Ooo "Lzkh "Ledmozerskoye" for Muyezerskiy
Found Hosteria Sampedro for Rawson
Found Caladh Inn for Stornoway
No hotel found...skipping.
Found Misty Waves Boutique Hotel for Hermanus
Found Collie Ridge for Collie
Found Codrington Gardens Bed And Breakfast for Codrington
Found Skjervøy fiskecamp AS for Skjervoy
Found Nuevo Hotel Plaza for Chuy
Found Grakas Lodge for Chongwe
Found Busta House Hotel for Brae
Found The George for Christchurch
No hotel found...skipping.
Found Tu Casa for East London
Found Skytterhuset for Hammerfest
Found Almost HOME for Qasigiannguit
Found Hotel El Recreo for General Roca
Found Posada del Inti Centro for Mercedes
Found Hostal de la Sierra Tandil for Tandil
Found The Hotel Petropavlovsky for Petropavlovsk-Kamchatskiy
No hotel found...skipping.
Found Far View Inn for Tibagi
Found Gostinichnyy Kompleks Aylgy for Zhigansk
Found Hotel Pousada Tordilho Negro for Marau
Found The Savanna Lodge for Kanye
No hotel found...skipping.
Found Magadan hotel for Magadan
Found Pension Feldgärtenhof for Lasa
Found Hotel Butembo for Butembo
Found Ron and Tony's Bed & Breakfast for Tuatapere
No hotel found...skipping.
Found Gostinitsa Karavan for Baykalovo
Found Gostinitsa for Kondinskoye
Found Hotel San Juan for Coquimbo
No hotel found...skipping.
Found Herdeiros de Antunes Capusso for Kuito
Found Comércio e Prestação de Serviços for Camabatela
Found Hotel Yura for Yura
Found Arctic View Glamping & Restaurant for Havoysund
Found Melodies Lodge for Mpika
Found McCracken Country Club for Victor Harbor
No hotel found...skipping.
Found Blue Bay Lodge for Saldanha
Found Gostinitsa V Apteke for Vitim
Found Sibiryachka for Strezhevoy
Found Krasnosel'kupnefteprodukt for Krasnoselkup
No hotel found...skipping.
Found Lolelunga Forest Reserve for Kasempa
Found Big Tree for Kabompo
Found Casablanca guest house and bar for Mpongwe
Found Budget Guesthouse Borgustova for Vagur
Found Hotel Konuk for Gerede
Found Grand Hotel for Bollnas
Found Hotel Arrarte for Rocha
Found Heimsjyen for Inndyr
Found Hotel Santa Cristina for Durazno
Found Vishera hotel for Krasnovishersk
Found Nordre Silda. for Raudeberg
Found Kinn Hotell Florø for Floro
Found The Hotel Shamrock for Bendigo
Found Gostinnitsa Medveditsa for Urengoy
Found Les Suites économique Murdochville for Murdochville
Found Airbnb rooms for Klaksvik
Found Tora Coastal Walk for Waipawa
Found Kvartira Posutochno V Sargatke for Sargatskoye
Found Hotel Casino San Eugenio del Cuareim for Artigas
Found Room4You for Setermoen
Found Residencial Karime for Taltal
Found Side Trax Inn for Beaverlodge
Found Hotel Estancia del Vaquero for Ocampo
Found Komfort Hotel for Megion
Found Chikago for Palana
Found Hotel Rukalaf for Chillan
Found Kingsgate Hotel Te Anau for Te Anau

In [33]:
hotel_df.count()

City                   110
Country                110
Max Temp               110
Current Description    110
Lat                    110
Lng                    110
Hotel Name             110
dtype: int64

In [34]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()

In [35]:
clean_hotel_df.count()

City                   110
Country                110
Max Temp               110
Current Description    110
Lat                    110
Lng                    110
Hotel Name             110
dtype: int64

In [54]:
clean_hotel_df.head(20)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
8,New Norfolk,AU,12.18,overcast clouds,-42.7826,147.0587,The Shingles Riverside Cottages
12,Keroka,KE,12.38,overcast clouds,-0.7758,34.9453,Bunker Hotel Keroka
15,Esperance,AU,12.91,broken clouds,-33.8667,121.9000,Hospitality Esperance
17,Busselton,AU,14.25,few clouds,-33.6500,115.3333,Observatory Guest House
19,Broken Hill,AU,13.95,few clouds,-31.9500,141.4333,Royal Exchange Hotel
20,Saskylakh,RU,11.56,broken clouds,71.9167,114.0833,
22,Beian,NO,13.34,broken clouds,63.6559,9.5683,"Fjord-Fishing AS, Property & Housing Co."
23,Mar Del Plata,AR,13.94,light rain,-38.0023,-57.5575,Gran Hotel Mar del Plata
34,Bredasdorp,ZA,10.06,light rain,-34.5322,20.0403,Bredasdorp Country Manor
37,Castro,BR,11.79,overcast clouds,-24.7911,-50.0119,CHACARA BAILLY
38,Anadyr,RU,10.00,broken clouds,64.7500,177.4833,Отке17.ру — жильё для командированных
44,Hobart,AU,12.37,broken clouds,-42.8794,147.3294,St Ives Hobart Accommodation Tasmania
54,Kaitangata,NZ,10.86,clear sky,-46.2817,169.8464,Kaitangata Motor Camp
56,Cape Town,ZA,12.99,light rain,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
59,Kodiak,US,12.27,light rain,57.7900,-152.4072,Best Western Kodiak Inn
74,Port Alfred,ZA,12.12,clear sky,-33.5906,26.8910,The Halyards Hotel
76,Port Lincoln,AU,14.26,broken clouds,-34.7333,135.8667,Port Lincoln Hotel
81,Ayan,RU,14.20,overcast clouds,56.4500,138.1667,Gostinitsa
83,Constitucion,CL,10.59,light rain,-35.3333,-72.4167,Hotel Boutique Las Azucenas
90,Khatanga,RU,14.97,clear sky,71.9667,102.5000,"""Khatanga"""

In [36]:
# 8a. Create the output File (CSV)
output_data_file = "../weather_database/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [57]:
# 9. Using the template add city name, the country code, 
#    the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °C</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [58]:
# 11a. Add a marker layer for each city to the map.
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))